# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dtd3.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dtd3.proto',
  package='dtd3',
  syntax='proto3',
  serialized_options=b'\n\020io.gRPC_dev.dtd3B\tDTD3ProtoP\001\242\002\004DTD3',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ndtd3.proto\x12\x04\x64td3\" \n\x0eLearnerRequest\x12\x0e\n\x06status\x18\x01 \x01(\x05\"$\n\x0e\x42ufferResponse\x12\x12\n\ntrain_data\x18\x01 \x01(\x0c\"%\n\x0bLearnerSend\x12\x16\n\x0enetwork_params\x18\x01 \x01(\x0c\"\x1e\n\x0c\x42ufferStatus\x12\x0e\n\x06status\x18\x01 \x01(\x05\x32\x82\x01\n\x07Learner\x12:\n\x08ReadData\x12\x14.dtd3.LearnerRequest\x1a\x14.dtd3.BufferResponse\"\x00\x30\x01\x12;\n\x0eUpdateNetworks\x12\x11.dtd3.LearnerSend\x1a\x12.dtd3.BufferStatus\"\x00(\x01\x42&\n\x10io.gRPC_dev.dtd3B\tDTD3ProtoP\x01\xa2\x02\x04\x44TD3b\x06proto3'
)




_LEARNERREQUEST = _descriptor.Descriptor(
  name='LearnerRequest',
  full_name='dtd3.LearnerRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='dtd3.LearnerRequest.status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=52,
)


_BUFFERRESPONSE = _descriptor.Descriptor(
  name='BufferResponse',
  full_name='dtd3.BufferResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='train_data', full_name='dtd3.BufferResponse.train_data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=90,
)


_LEARNERSEND = _descriptor.Descriptor(
  name='LearnerSend',
  full_name='dtd3.LearnerSend',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='network_params', full_name='dtd3.LearnerSend.network_params', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=129,
)


_BUFFERSTATUS = _descriptor.Descriptor(
  name='BufferStatus',
  full_name='dtd3.BufferStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='dtd3.BufferStatus.status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=131,
  serialized_end=161,
)

DESCRIPTOR.message_types_by_name['LearnerRequest'] = _LEARNERREQUEST
DESCRIPTOR.message_types_by_name['BufferResponse'] = _BUFFERRESPONSE
DESCRIPTOR.message_types_by_name['LearnerSend'] = _LEARNERSEND
DESCRIPTOR.message_types_by_name['BufferStatus'] = _BUFFERSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LearnerRequest = _reflection.GeneratedProtocolMessageType('LearnerRequest', (_message.Message,), {
  'DESCRIPTOR' : _LEARNERREQUEST,
  '__module__' : 'dtd3_pb2'
  # @@protoc_insertion_point(class_scope:dtd3.LearnerRequest)
  })
_sym_db.RegisterMessage(LearnerRequest)

BufferResponse = _reflection.GeneratedProtocolMessageType('BufferResponse', (_message.Message,), {
  'DESCRIPTOR' : _BUFFERRESPONSE,
  '__module__' : 'dtd3_pb2'
  # @@protoc_insertion_point(class_scope:dtd3.BufferResponse)
  })
_sym_db.RegisterMessage(BufferResponse)

LearnerSend = _reflection.GeneratedProtocolMessageType('LearnerSend', (_message.Message,), {
  'DESCRIPTOR' : _LEARNERSEND,
  '__module__' : 'dtd3_pb2'
  # @@protoc_insertion_point(class_scope:dtd3.LearnerSend)
  })
_sym_db.RegisterMessage(LearnerSend)

BufferStatus = _reflection.GeneratedProtocolMessageType('BufferStatus', (_message.Message,), {
  'DESCRIPTOR' : _BUFFERSTATUS,
  '__module__' : 'dtd3_pb2'
  # @@protoc_insertion_point(class_scope:dtd3.BufferStatus)
  })
_sym_db.RegisterMessage(BufferStatus)


DESCRIPTOR._options = None

_LEARNER = _descriptor.ServiceDescriptor(
  name='Learner',
  full_name='dtd3.Learner',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=164,
  serialized_end=294,
  methods=[
  _descriptor.MethodDescriptor(
    name='ReadData',
    full_name='dtd3.Learner.ReadData',
    index=0,
    containing_service=None,
    input_type=_LEARNERREQUEST,
    output_type=_BUFFERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateNetworks',
    full_name='dtd3.Learner.UpdateNetworks',
    index=1,
    containing_service=None,
    input_type=_LEARNERSEND,
    output_type=_BUFFERSTATUS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_LEARNER)

DESCRIPTOR.services_by_name['Learner'] = _LEARNER

# @@protoc_insertion_point(module_scope)
